import { messages as enMessages } from '../messages/en'
import { pseudoLocalizeMessages } from '../pseudo'

const pseudoMessages = pseudoLocalizeMessages(
  enMessages as unknown as Record<string, string>
)

const lines = Object.entries(pseudoMessages)
  .map(([key, value]) => `  '${key}': '${value.replace(/'/g, "\\'")}'`)
  .join(',\n')

const output = `// auto-generated by pseudo-gen.ts - do not edit manually
import type { Messages } from '../types'

export const messages: Record<keyof Messages, string> = {
${lines},
}
`

await Bun.write(new URL('../messages/_pseudo.ts', import.meta.url).pathname, output)
console.info('generated _pseudo.ts')
